illionillion/CIRCLIA

.eslintignore, .eslintrc.json, README.md, lefthook.yml, nextjs-app/.eslintrc.json, nextjs-app/app/layout.tsx, nextjs-app/app/login/page.tsx, nextjs-app/app/page.tsx, nextjs-app/components/layouts/app-layout.tsx, nextjs-app/package-lock.json, nextjs-app/package.json, nextjs-app/utils/random.ts, package-lock.json, package.json
=> ホーム画面のコーディング完了

nextjs-app/app/circles/page.tsx, nextjs-app/app/page.tsx, nextjs-app/components/data-display/circle-card.tsx, nextjs-app/components/layouts/app-layout.tsx
=> サークル一覧画面作成

.commitlintrc, README.md, lefthook.yml, package-lock.json, package.json
=> comit-lint追加

nextjs-app/app/circles/edit/page.tsx
=> サークル編集画面を作成

README.md, app/circles/[circle_id]/[tab_key]/page.tsx, app/circles/[circle_id]/page.tsx, components/layouts/circle-detail-page.tsx
=> コンポーネントの分割

.github/dependabot.yml
=> chore: dependabot.yml追加

data/circle.ts
Closes #58  
https://github.com/ocs-amo/amo/pull/57#pullrequestreview-2394086359
=> fix: 退会してない場合のみ取得できるように修正

components/data-display/member-card.tsx, prisma/ERD.md
Related #69  
メンバー一覧で権限を変更する時、ダイアログを表示する
「（選択したメンバー名）さんの役割を（現在の権限）から（変更したい権限）に変更しますか？」と表示
削除ダイアログは未作成
=> 権限ダイアログの作成

actions/circle/fetch-activity.ts, components/data-display/circle-activitydays.tsx, data/activity.ts
=> fix: サークル一覧取得を`circleId`で絞れるように修正

actions/circle/toggle-activity.ts, components/data-display/circle-activitydays.tsx, data/activity.ts, prisma/schema.prisma
=> サークル活動の参加・キャンセルの処理実装

actions/circle/edit-activity.ts, actions/circle/remove-activity.ts, app/circles/[circle_id]/activities/[activity_id]/edit/page.tsx, components/data-display/circle-activitydays.tsx, components/forms/activity-form.tsx, data/activity.ts, utils/format.ts
=> 活動日編集・削除実装

app/circles/[circle_id]/activities/[activity_id]/edit/page.tsx, app/circles/[circle_id]/activities/new/page.tsx, app/circles/[circle_id]/page.tsx, data/activity.ts
Closes # 
`circles/[存在しないサークルID]/activities/new`や`circles/[存在しないサークルID]/activities/[存在しない活動ID]/edit`などでページが表示されないように修正した。
=> fix: 存在しないパラメタでページを表示しないようにした

actions/circle/fetch-activity.ts, app/circles/[circle_id]/activities/[activity_id]/page.tsx, components/data-display/circle-activitydays.tsx, components/disclosure/circle-detail-tabs.tsx, components/forms/activity-menu-button.tsx, components/layouts/circle-detail-page.tsx, data/activity.ts
=> feat: 活動表示画面実装

actions/circle/update-role.ts, data/circle.ts
Closes #104  
メンバーの権限変更・削除時にIDが表示されるのでそれをユーザー名を表示するように修正する
=> Bug user name

.gitignore, README.md, lefthook.yaml, package.json, prisma/schema.prisma
=> build: httpsの設定追加

actions/circle/create-circle.ts, actions/circle/update-circle.ts, app/circles/[circle_id]/[tab_key]/page.tsx, app/circles/[circle_id]/activities/[activity_id]/edit/page.tsx, app/circles/[circle_id]/activities/[activity_id]/page.tsx, app/circles/[circle_id]/activities/new/page.tsx, app/circles/[circle_id]/announcement/[topic_id]/edit/page.tsx, app/circles/[circle_id]/announcement/[topic_id]/page.tsx, app/circles/[circle_id]/announcement/create/page.tsx, app/circles/[circle_id]/edit/page.tsx, app/circles/[circle_id]/page.tsx, app/circles/[circle_id]/thread/[topic_id]/edit/page.tsx, app/circles/[circle_id]/thread/[topic_id]/page.tsx, app/circles/[circle_id]/thread/create/page.tsx, app/layout.tsx, components/forms/circle-form.tsx, components/layouts/app-layout.tsx, package.json, pnpm-lock.yaml, server.ts, setup.sh, tsconfig.json
Closes # 
- カスタムサーバー追加
- `dynamic: "force-dynamic"`設定
- 起動用スクリプト作成
- ubuntu起動時に実行
=> 学内サーバー用の設定追加

README.md, actions/circle/fetch-circle.ts, app/circles/[circle_id]/[tab_key]/page.tsx, app/circles/[circle_id]/activities/[activity_id]/edit/page.tsx, app/circles/[circle_id]/activities/[activity_id]/page.tsx, app/circles/[circle_id]/announcement/[topic_id]/edit/page.tsx, app/circles/[circle_id]/announcement/[topic_id]/page.tsx, app/circles/[circle_id]/edit/page.tsx, app/circles/[circle_id]/page.tsx, app/circles/[circle_id]/thread/[topic_id]/edit/page.tsx, app/circles/[circle_id]/thread/[topic_id]/page.tsx, components/forms/activity-form.tsx, data/circle.ts, setup.sh
Closes # 
試しにREADMEの情報を参考にしてビルドして動作チェックをお願いします。
@AQUA-room @ymmyo5
=> docs: ビルド関連追加

app/user/[user_id]/page.tsx, components/data-display/activity-card.tsx
=> feat: 参加者一覧表示

components/layouts/circles-page.tsx
Closes #123  
検索欄の背景を白→大理石に変更
backgroundColorを削除しbackgroundImageに変更したら大理石が若干透けていたのでColorも残したままImage追加
=> fix: 検索欄の背景を大理石に変更

app/user/[user_id]/page.tsx, components/data-display/member-request-card.tsx
=> プロフィールからTeamsにアクセスできるように修正

components/layouts/app-layout.tsx
Closes #133 
<li>メッセージ</li>
<li>設定</li>
<li>カレンダー（1day）</li>
<br>
がいらなくなったので削除する
=> refactor:サイドバーから不要になった項目の削除

components/forms/signin-form.tsx, components/layouts/app-layout.tsx
=> [新機能] - ログイン画面のデザイン

components/forms/activity-form.tsx, components/forms/circle-form.tsx, components/forms/profile-form.tsx, components/layouts/circles-page.tsx
Closes #136  
ボタンの色統一だけ実装しました。
=> feat:color uniformity

components/data-display/week-calendar.tsx, components/forms/activity-menu-button.tsx, components/forms/album-form.tsx, components/forms/announcement-form.tsx, components/forms/thread-form.tsx
=> ボタン色修正漏れ修正

components/data-display/circle-activitydays.tsx, components/data-display/circle-threads.tsx, components/forms/circle-form.tsx, theme/index.ts, theme/styles/global-style.ts
Closes # 
全てのテキストボックスの背景を変えてわかりやすいようにした。
=> 全てのテキストボックスの背景修正

components/data-display/circle-activitydays.tsx
=> 活動日のMonthPickerをボタンでも移動できるように修正

package.json, pnpm-lock.yaml
=> chore: 依存関係修正

components/data-display/activity-card.tsx, components/data-display/circle-activitydays.tsx, components/data-display/circle-albums.tsx, components/data-display/member-card.tsx, components/data-display/member-request-card.tsx, components/data-display/notification-list-item.tsx, components/data-display/thread-item.tsx, components/forms/activity-form.tsx, components/forms/circle-form.tsx, components/forms/profile-form.tsx, components/layouts/circles-page.tsx
=> fix: 全ての`LinkOverlay`を`next/link`化

package.json, pnpm-lock.yaml
Reverts ocs-amo/amo#159
@AQUA-room @ymmyo5 
これはApproveしてマージしてくれるだけでOK
=> Revert "chore: 依存関係修正"

components/data-display/album-card.tsx, components/data-display/circle-albums.tsx
=> feat:carouselの色変更

data/activity.ts, package.json, pnpm-lock.yaml
Closes # 
ローカル環境での動作確認と、デプロイ環境での動作確認を行ってください。
@AQUA-room
=> fix: タイムゾーン修正

components/layouts/app-layout.tsx, components/layouts/circles-page.tsx
=> ヘッダー・ナビバーの固定とモバイル時のフッターバー表示

components/forms/activity-form.tsx, components/forms/announcement-form.tsx, components/forms/circle-form.tsx, components/forms/signin-form.tsx, components/forms/thread-form.tsx
Closes #170 
各フォームにおいて作成選択後、画面遷移もしくはエラーが起こるまでクリックできないようにする。
=>  [新機能] - 各フォーム作成時の操作不能状態の調整

app/layout.tsx, components/layouts/app-layout.tsx, package.json, pnpm-lock.yaml
Closes # 
アナリティクス・インサイト計測のプラグイン追加
ローカルでの動作チェックだけして問題なければマージしてください。
=> chore: vercelのプラグイン追加

components/layouts/app-layout.tsx
Closes #175 
ロゴをクリックすることでホームに移動するように変更
=> [新機能] - ヘッダーのロゴ画像へのリンク追加

components/forms/thread-form.tsx
=> refactor:スレッド作成の「詳細」欄を「説明」欄に変更

components/data-display/thread-card.tsx
=> [新機能] - 掲示板のスレッド内のメッセージ投稿で、プレースホルダを表示

components/forms/album-form.tsx, schema/album.ts
Closes #181 
アルバム作成時の「内容」の入力必須を解除
=> [新機能] - アルバム作成画面の内容欄は必須を外す

components/layouts/app-layout.tsx
=> feat:通知アイコンを上部に変更

app/user/[user_id]/page.tsx, components/forms/activity-form.tsx, components/forms/album-form.tsx, components/forms/announcement-form.tsx, components/forms/circle-form.tsx, components/forms/profile-form.tsx, components/forms/thread-form.tsx, components/layouts/circle-detail-page.tsx, components/navigation/pagination-list.tsx, theme/styles/global-style.ts
Closes # 
モバイル時にフッターにボタンが隠れるバグ修正
=> モバイル時にフッターにボタンが隠れるバグ修正

components/layouts/app-layout.tsx
Closes #175 #191 
Linkの記述形式の修正をしました
=> [修正] - ヘッダーのロゴ画像へのリンク追加

components/forms/circle-form.tsx
Closes #177 
サークル作成画面の「活動日」「活動場所」のプレースホルダに例を追加
=> [新機能] - サークル作成画面で「活動日」や「活動場所」の例の表示

components/forms/circle-detail-button.tsx, components/layouts/app-layout.tsx
Closes #178 
活動日程／アルバム／掲示板画面の「＋追加」「＋作成」ボタンを右下に移動
=> [新機能] - 追加、作成ボタンを移動

components/forms/album-form.tsx
Closes #203 
アルバム作成画面の作成・キャンセルボタンを右下に固定
=> [新機能] - モバイル時のアルバム作成ボタンの配置変更

components/data-display/notification-list.tsx, components/navigation/pagination-list.tsx
Closes #210  
- 位置がズレるのを修正
- ホームの方で3個ずつ表示されるように修正
=> ページネーション修正

components/layouts/app-layout.tsx
Closes #201 
モバイル表示時のナビゲーションバーの並び順を
お知らせ、サークル一覧、ホーム、カレンダー、プロフィール
に変更
=> [新機能] - モバイル時のナビゲーションバーの配置変更

components/forms/activity-form.tsx, components/forms/album-form.tsx, components/forms/announcement-form.tsx, components/forms/profile-form.tsx, components/forms/thread-form.tsx, components/layouts/app-layout.tsx
Closes #204 
各作成機能のプレースホルダを変更
例）○○
サークル作成
活動日程
アルバム
お知らせ
掲示板
プロフィール入力欄
=> [新機能] - すべての作成機能にプレースホルダを追加

components/forms/circle-detail-button.tsx, components/layouts/circle-detail-page.tsx
Closes #185  
権限ユーザの場合、サークル編集ボタンを
メンバー一覧のみ→活動日程・アルバム・掲示板・メンバー一覧すべて
で表示するように変更
=> feat: サークル編集のボタンを全タブで表示するように変更

components/forms/activity-form.tsx
Closes # 
見出し、内容、日付、場所、開始時刻、終了時刻、備考を、
見出し、内容、日付、開始時刻、終了時刻、場所、備考に変更
=> refactor: 活動日程作成画面と編集画面の場所を終了時刻の下に変更

actions/circle/fetch-circle.ts, actions/user/user.ts, app/page.tsx, app/user/[user_id]/page.tsx
=> fix: 講師の場合はプロフィールに講師担当サークル一覧を表示

actions/circle/membership-request.ts
=> feat:退会時のユーザー名表示

components/data-display/circle-threads.tsx, components/data-display/thread-card.tsx, next.config.mjs, package.json, pages/api/socketio.ts, pnpm-lock.yaml
=> スレッド画面でのリアルタイム通信成功

components/data-display/circle-members.tsx, components/data-display/member-request-card.tsx, package.json, pnpm-lock.yaml
Closes # 
メンバー追加が完了するまでローディング状態にして２重で処理できないようにした。
=> メンバー承認が２重でできないように修正

components/layouts/app-layout.tsx, components/layouts/circles-page.tsx, theme/styles/global-style.ts
=> [バグ] - 画面サイズによる画像の繰り返し

components/data-display/circle-activitydays.tsx, components/data-display/circle-albums.tsx, components/data-display/circle-threads.tsx, components/forms/circle-detail-button.tsx
=> fix: ボタンの位置変更

components/data-display/week-calendar.tsx, components/forms/activity-form.tsx, components/layouts/calendar.tsx, utils/format.ts
=> feat:カレンダーの土曜日を青に変更

components/data-display/week-calendar.tsx, components/forms/activity-form.tsx, components/layouts/calendar.tsx, utils/format.ts
Reverts illionillion/CIRCLIA#198
=> Revert "feat:カレンダーの土曜日を青に変更"

components/data-display/circle-activitydays.tsx, components/data-display/circle-threads.tsx
=> 活動日のレイアウト崩れ修正

@types/next-auth.d.ts, actions/circle/membership-request.ts, auth.config.ts, auth.ts, data/circle.ts, utils/mail.ts
Closes #233 
APIそのものの権限の問題でアプリから送ることはできなかったので個人のメールから送るようにした。
後々、用途によってメッセージを切り替えてメールを送る関数などにする予定。
=> 入会申請時にOutlookからメール送信

components/data-display/member-request-card.tsx
=> fix: 承認・拒否処理中に反対側のボタンも押せないように修正

components/forms/signin-form.tsx, components/media-and-icons/microsoft-icon.tsx
=> Microsoftのアイコンをサインイン画面に追加

components/forms/signin-form.tsx
=> fix: ボタンスタイル修正

data/activity.ts
Closes #252 
検証のしようがないので、ローカル環境でイベントを色々登録して月ピッカーを切り替えてもデグレなどの問題がなければ一旦マージしてください。
それでも解決しなければ別アプローチを考えます。
=> fix: 時差調整追加

actions/circle/membership-request.ts
=> feat: 入会時にメール送信の処理追加

components/data-display/circle-activitydays.tsx
Closes   
さっきの #253 で治っていなかったのでデバッグ用のログ出力を追加しました。
一度マージしてください。 @AQUA-room
=> fix: デバッグ用のログ追加

components/data-display/circle-activitydays.tsx
=> fix: monthPicker変更時の処理修正

components/data-display/week-calendar.tsx, components/forms/activity-form.tsx, components/layouts/calendar.tsx, utils/format.ts
Reverts illionillion/CIRCLIA#237
@pepsisssa このブランチで作業して
=> Revert "Revert "feat:カレンダーの土曜日を青に変更""

app/page.tsx, components/layouts/notification-page.tsx
Closes #258 
- ホーム画面のアンダーバー（Separator）の色指定を削除
- お知らせ画面のアンダーバー（Separator）自体を削除
=> fix: アンダーバーカラー変更と削除

app/page.tsx, components/data-display/circle-list.tsx, components/navigation/pagination-grid.tsx
Closes #269  
講師アカウントでログインして、講師担当サークル・所属サークルをたくさん増やしていろんな画面幅でチェックしてください。
余程崩れるとかでなければ妥協。
一般アカウントでも確認お願いします。
=> ホームのサークル一覧のページネーション追加

actions/circle/membership-request.ts
Related #267 
入会・退会に関する動作テストしてる最中でPC落ちたので動作確認できてません。。
ただ入会申請の承認でエラー出てたので見直す必要あるかも（ちなみにリロードしたら処理は完了してた）
=> fix: メール送信に関するコードをコメントアウト

components/layouts/app-layout.tsx
=> fix: メニューボタン押すと閉じるように修正

actions/circle/create-circle.ts, actions/circle/update-circle.ts, components/forms/circle-form.tsx, data/circle.ts
Closes #215  
- 作成時に同じサークル名があればエラー
- 編集時に自分以外のサークルで同じ名前があればエラー
この条件になるように修正しました。
チェックお願いします。
=> fix: 同名のサークルを作れないように修正

components/data-display/announcement-card.tsx, components/data-display/circle-threads.tsx, components/data-display/thread-card.tsx, components/data-display/thread-item.tsx
Closes #271  
複数アカウントで退会・入会繰り返しながらスレッドの作成編集削除を試してください。
=> fix: 退会したメンバーはスレッドを編集削除できないように画面上の処理は修正

components/data-display/thread-card.tsx
=> fix: スレッドの送信ボタンのアイコン修正

data/album.ts
Closes #230 
アルバム作成が最新のものから表示されるように変更
作成日時でソートするようにしたけど、
更新されたらまた一番前に表示するべき？🤔
=> feat: アルバムに降順ソート

.github/workflows/quality.yml, README.md, actions/notification/index.ts, app/layout.tsx, components/forms/push-notification-button.tsx, components/layouts/notification-page.tsx, data/notification.ts, middleware.ts, package.json, pnpm-lock.yaml, prisma/ERD.md, prisma/migrations/20241229053637_init/migration.sql, prisma/migrations/20241230100815_init/migration.sql, prisma/schema.prisma, public/sw.js, utils/add-sw.ts, utils/web-push.ts
Closes #294  
#293 で実装した通知のタイミングでブラウザ通知の許可をしているとプッシュ通知を飛ばせるように実装した。
PCのChromeでは通知は表示されないが、Safariでは表示された。
ローカル環境を実機でデバッグするのはめんどくさいのでこのままマージしてデプロイ環境でスマホからアクセスして試します。
環境変数の情報が変わっているので、動作確認・マージした際はREADMEに従い初期設定をやり直す必要あり。
=> WebPushの実装

components/forms/push-notification-button.tsx
Closes #306 
イシュー参照
Chromeブラウザで成功時に成功メッセージ、シークレットタブなどで失敗時にエラー表示が確認できればOK
=> プッシュ通知の許可の成功失敗時のメッセージ表示実装

components/data-display/activity-card.tsx, components/forms/google-calendar-button.tsx
=> Googleカレンダーへのリンクボタンを追加

components/layouts/circle-detail-page.tsx
=> fix: モバイル時だけヘッダーを開閉するように修正

components/navigation/pagination-grid.tsx
=> fix: ホーム画面のサークルのページネーションカラーをリバーブルーに変更

components/data-display/album-card.tsx, components/data-display/notification-list-item.tsx, components/disclosure/circle-detail-tabs.tsx, components/forms/google-calendar-button.tsx, components/layouts/app-layout.tsx, components/navigation/pagination-list.tsx
=> ページネーション、通知カラーをリバーブルに変更

components/data-display/custom-graph.tsx, components/layouts/circles-page.tsx
Closes # 
@AQUA-room 緊急でマージしてほしい
=> fix: 余計なログ削除、意図しないクリックを防止

components/data-display/custom-graph.tsx, components/layouts/circles-page.tsx
Closes # 
@AQUA-room 
これも緊急でマージお願いします。
=> fix: 画像が表示されるように修正

prisma/seed.ts, prisma/seeds/circle-albums.ts, prisma/seeds/circle-topics.ts
=> chore: 初期データ追加

components/forms/profile-form.tsx
=> fix: 横幅大きく・コンポーネントを外側に移動

actions/circle/announcement.ts, actions/circle/membership-request.ts, actions/circle/thread.ts
Closes #315  
@ymmyo5 @AQUA-room ローカルでのデバックは難しいのでマージしてから本番環境で確認お願いします。
=> fix: 通知のタイトル文言修正

actions/circle/announcement.ts, actions/circle/membership-request.ts
Related #330  
お知らせなどのタイトル部分がおかしくなっていたので修正。
=> fix: タイトル部分の文言修正

app/circles/[circle_id]/activities/[activity_id]/page.tsx, components/data-display/week-calendar.tsx, data/activity.ts
Related #337  
@AQUA-room @ymmyo5 
ローカルでは再現せずに本番環境でのタイムゾーンの問題なので一旦マージお願いします。
=> 週間カレンダーの活動日がズレる問題の修正

data/activity.ts
=> fix: luxionのみに修正

components/data-display/circle-activitydays.tsx, components/data-display/circle-albums.tsx, components/data-display/member-card.tsx, components/data-display/thread-item.tsx, components/forms/activity-menu-button.tsx
=> fix: サークル内のホバー全て削除

components/data-display/custom-graph.tsx
=> fix: 「PC推奨」のテキスト追加

components/disclosure/circle-detail-tabs.tsx
=> fix: タブパネル部分の高さを修正

components/disclosure/circle-detail-tabs.tsx
=> fix: タブによって高さを切り替えれるように修正

components/data-display/circle-activitydays.tsx
Closes # 
https://github.com/user-attachments/assets/be38f23f-616e-4ec3-9158-839faafccfdf
=> fix: 月末時に次の月に移動できないバグ修正

components/data-display/circle-welcome.tsx
Closes #352  
編集ボタンの位置を他の画面と同じ場所に配置しました。
=> feat:編集ボタンの位置変更

actions/circle/fetch-activity.ts, components/data-display/circle-activitydays.tsx
Closes # 
@AQUA-room @ymmyo5 
本番環境でしか起こらないバグだったので一度マージして確認して欲しいです
=> fix: タイムゾーン周り修正

actions/suggestion/index.ts, components/data-display/circle-activitydays.tsx, components/data-display/week-calendar.tsx, components/media-and-icons/network-animation.tsx, components/media-and-icons/robot-animation.tsx
=> fix: 不要なログ削除

components/layouts/circles-page.tsx
=> feat:該当するサークルがない場合にメッセージの表示

components/layouts/circles-page.tsx
=> AI検索の閾値変更をスライダーに変更

components/data-display/custom-graph.tsx
Closes # 
キーワードは9文字以上の時に`...`で省略、サークル名は10文字以上の時に`...`で省略するようにしました。
いろんな長さのワードで検索したりして、はみ出たり崩れたり、クリック範囲がずれないか試してからマージしてください。
=> fix: カードのサイズを均一に修正

components/data-display/custom-graph.tsx, components/layouts/circles-page.tsx
=> fix: カードのサイズ変更・スライダーの装飾カスタマイズ

components/layouts/app-layout.tsx
=> fix: ヘッダーのリンクテキストの幅修正

components/forms/profile-form.tsx, theme/styles/global-style.ts
=> fix: `react-md-editor`のアイコンサイズを修正

package.json, pnpm-lock.yaml
=> `esbuild`のバージョンオーバーライド

package.json, pnpm-lock.yaml
=> fix: `serialize-javascript`アップデート
